version = 1

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/chiyutianyi/sourcegraph"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]

[[transformers]]
name = "gofmt"